version: '2'
volumes:
    mosquitto:
    mysql-data:
services:
  raspberrypirfid:
    build: ./raspberrypirfid
    privileged: true
    expose:
      - "80"
    environment:
      - MQTT_SA=mosquitto
      - MQTT_SP=1883
  update-server:
    build: ./update-server
    expose:
      - "8081"
    ports:
      - "0.0.0.0:8081:8081"
    networks:
      - default
      - mosquitto
  mosquitto:
    image: eclipse-mosquitto:1.6.14
    hostname: mosquitto
    container_name: mosquitto
    expose:
      - "1883"
      - "9001"
    ports:
      - "0.0.0.0:1883:1883"
      - "0.0.0.0:9001:9001"
    volumes:
      - mosquitto:/mosquitto/config/
    networks:
      - default
      - mosquitto
  mysql:
    image: jsurf/rpi-mariadb:latest
    hostname: mysql
    container_name: mysql
    expose:
      - "3306"
    ports:
      - "0.0.0.0:3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - default
      - mysql
  mysql-fill:
    build: ./mysql
    container_name: mysql-fill
    networks:
      - default
      - mysql
  backend:
    build: ./backend
    expose:
      - "8080"
    ports: 
      - "0.0.0.0:8080:8080"
    environment:
      - MQTT_SA=mosquitto
      - MQTT_SP=1883
      - MYSQL_SA=mysql
      - MYSQL_SP=3306
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_U=iot
      - MYSQL_P=1234
    networks:
      - default
networks:
  mysql:
    driver: "bridge"
  mosquitto:
    driver: "bridge"
