FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3.8-buster-build
# Defines our working directory in container
WORKDIR /usr/src/app

RUN install_packages wget

RUN apt-get update -y \
    && apt-get install python


# This will copy all files in our root to the working  directory in the container
COPY . ./
RUN pip install -r requirements.txt


# server.js will run when container starts up on the device
CMD ["python3", "picode.py"]
