FROM opensuse/tumbleweed

RUN zypper --non-interactive install gcc git which neovim vim python2 python2-pip python-xml wget tar exa fzf fzf-tmux curl zsh gzip make bison ncurses-devel ncurses-utils flex sysuser-tools sudo
# CMD useradd --create-home -b "/" --shell "/usr/bin/bash" --uid "10001" work -G root
# USER work:work
WORKDIR /work
RUN yes | pip2  install --upgrade pip
RUN wget https://raw.githubusercontent.com/espressif/ESP8266_RTOS_SDK/master/requirements.txt
RUN yes | pip2 install -r requirements.txt
RUN mkdir -p /toolchain 
WORKDIR /toolchain
RUN wget https://dl.espressif.com/dl/xtensa-lx106-elf-gcc8_4_0-esp-2020r3-linux-amd64.tar.gz -O xtensa.tar.gz
RUN pwd && ls
RUN pwd && tar xvf xtensa.tar.gz
ENV PATH="${PATH}:/toolchain/xtensa-lx106-elf/bin/"
ENV IDF_PATH="/work/ESP8266_RTOS_SDK"
WORKDIR /work/ESP8266_RTOS_SDK
RUN mkdir -p /work/ESP8266_RTOS_SDK
